import mongoose, { type HydratedDocument, type InferSchemaType, type Model } from "mongoose";

import { CATEGORIES } from "@/lib/categories";

/**
 * @file A proposed or agreed trade between two sites.
 *
 * `siteA` is always the lexicographically smaller ObjectId. Combined with the
 * unique compound index on `(siteA, siteB)`, that means an unordered pair maps
 * to exactly one document no matter which side the match was generated from.
 * This is a direct translation of the one genuinely elegant piece of the
 * reference implementation's Postgres schema (`check (site_a_id < site_b_id)`
 * plus `unique (site_a_id, site_b_id)`), and it is what keeps two concurrent
 * matching runs from creating duplicate threads for the same pair.
 *
 * There are no email aliases here. The reference's double-blind relay is
 * deliberately not ported: partner domains and emails stay hidden through every
 * read path until `state` reaches `agreed`, and at that moment both sides are
 * revealed to each other and talk directly. Where each link lands is then
 * entirely up to them.
 */

export const MATCH_STATES = [
    /** Created by matching. Neither side has responded. */
    "proposed",
    "a_accepted",
    "b_accepted",
    /** Both sides in. Domains and emails are revealed from here on. */
    "agreed",
    /** Both links verified live at least once. */
    "placed",
    "declined",
    "expired",
] as const;
export type MatchState = (typeof MATCH_STATES)[number];

const ExchangeMatchSchema = new mongoose.Schema(
    {
        siteA: { type: mongoose.Schema.Types.ObjectId, ref: "ExchangeSite", required: true },
        siteB: { type: mongoose.Schema.Types.ObjectId, ref: "ExchangeSite", required: true },

        category: { type: String, required: true, enum: CATEGORIES },
        /** Score from the matching engine at creation time, kept for tuning. */
        score: { type: Number, default: 0 },
        /** True when the pair came from a widened (adjacent) category pool. */
        widened: { type: Boolean, default: false },

        state: { type: String, enum: MATCH_STATES, default: "proposed", required: true },
        /** Null when generated by auto-pair or the weekly cron. */
        proposedBy: { type: mongoose.Schema.Types.ObjectId, default: null },
        declineReason: { type: String, default: null },

        /** The reveal moment. Before this, neither side knows the other's domain. */
        agreedAt: { type: Date, default: null },
        expiresAt: { type: Date, required: true },
    },
    { timestamps: true, collection: "exchange_matches" },
);

ExchangeMatchSchema.index({ siteA: 1, siteB: 1 }, { unique: true });
ExchangeMatchSchema.index({ state: 1, expiresAt: 1 });

export type ExchangeMatchDoc = InferSchemaType<typeof ExchangeMatchSchema>;

export const ExchangeMatch: Model<ExchangeMatchDoc> =
    (mongoose.models.ExchangeMatch as Model<ExchangeMatchDoc>) ||
    mongoose.model<ExchangeMatchDoc>("ExchangeMatch", ExchangeMatchSchema);

/**
 * Orders an unordered pair so it maps to exactly one document.
 *
 * Every read and write touching a pair must go through this. Skipping it
 * reintroduces the duplicate-thread bug the unique index exists to prevent.
 */
export function orderPair<T extends { toString(): string }>(x: T, y: T): [T, T] {
    return x.toString() < y.toString() ? [x, y] : [y, x];
}

/** Whether a match has reached the point where identities are revealed. */
export function isRevealed(state: MatchState): boolean {
    return state === "agreed" || state === "placed";
}

/**
 * A live document as returned by queries: ExchangeMatchDoc plus `_id` and the Mongoose
 * document methods. `InferSchemaType` describes the SHAPE of the schema and
 * deliberately omits `_id`, so passing a query result where a plain ExchangeMatchDoc is
 * expected typechecks but loses the id. Service signatures should take this.
 */
export type ExchangeMatchHydrated = HydratedDocument<ExchangeMatchDoc>;
